[project]
name = "goods-vault-backend"
version = "0.1.0"
description = "API for Goods Vault"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "pydantic-settings>=2.8.1",
    "typer>=0.15.2",
    "uvicorn>=0.34.1",
]
